[pytest]
addopts = -v --junitxml=reports/report.xml --html=reports/report.html --self-contained-html
testpaths = tests
python_files = test_*.py

# This makes imports like "from src.api.client import APIClient" work
pythonpath = .

markers =
    api: API tests
    ui: UI tests
    smoke: Smoke tests
    smoke: Smoke tests
