[pytest]
addopts = -v --junitxml=reports/report.xml
testpaths = tests
python_files = test_*.py

# This makes imports like "from src.api.client import APIClient" work
pythonpath = .

markers =
    api: API tests
    smoke: Smoke tests
